
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VerchoturcevQuest
{

using System;
    using System.Collections.Generic;
    
public partial class GAnswer
{

    public int ID { get; set; }

    public string Text { get; set; }

    public bool IsCorrect { get; set; }

    public int IDqs { get; set; }



    public virtual GQuestion GQuestion { get; set; }

}

}
