
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VerchoturcevQuest
{

using System;
    using System.Collections.Generic;
    
public partial class GQuestion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GQuestion()
    {

        this.GAnswer = new HashSet<GAnswer>();

    }


    public int ID { get; set; }

    public string Text { get; set; }

    public int Type { get; set; }

    public int IDts { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GAnswer> GAnswer { get; set; }

    public virtual GTest GTest { get; set; }

}

}
