
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VerchoturcevQuest
{

using System;
    using System.Collections.Generic;
    
public partial class GTestResult
{

    public int ID { get; set; }

    public string Name { get; set; }

    public string Group { get; set; }

    public System.DateTime Date { get; set; }

    public int Result { get; set; }

    public int IDts { get; set; }



    public virtual GTest GTest { get; set; }

}

}
