

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VerchoturcevQuest
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TestDBEntities : DbContext
{
    public TestDBEntities()
        : base("name=TestDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<GAnswer> GAnswer { get; set; }

    public virtual DbSet<GQuestion> GQuestion { get; set; }

    public virtual DbSet<GTest> GTest { get; set; }

    public virtual DbSet<GTestResult> GTestResult { get; set; }

}

}

